resources:
- repo: self

phases:

- phase: Windows64bit
  queue:
    name: 'Hosted VS2017'
    
  steps:
  - task: CMake@1
    displayName: 'CMake .. -G"Visual Studio 15 2017 Win64"'
    inputs:
      cmakeArgs: '.. -G"Visual Studio 15 2017 Win64"'

  - task: MSBuild@1
    displayName: 'Build solution build/IscsiLibrary.sln'
    inputs:
      solution: build/IscsiLibrary.sln
      msbuildArguments: '/m /p:Configuration=Release /target:AllTest'
  - script: 'AllTest.exe'
    workingDirectory: build/lib/all_test/Release/
    displayName: 'Run Tests'

- phase: LinuxSelfHost
  queue:
    name: 'Hosted Ubuntu 1604'
  steps:
  - task: CMake@1
    displayName: 'cmake'
  - script: 'make AllTest'
    displayName: 'Build AllTest'
  - script: './AllTest.out'
    workingDirectory: lib/all_test/
    displayName: 'run AllTest'
    
