resources:
- repo: self

phases:

- phase: Windows64bit
  queue:
    name: 'Hosted VS2017'
    
  steps:
  - task: CMake@1
    displayName: 'CMake .. -G"Visual Studio 15 2017 Win64"'
    inputs:
      cmakeArgs: '.. -G"Visual Studio 15 2017 Win64"'

  - task: MSBuild@1
    displayName: 'Build solution build/IscsiLibrary.sln'
    inputs:
      solution: build/IscsiLibrary.sln
      msbuildArguments: '/m /p:Configuration=Release /target:AllTest'
  - script: 'AllTest.exe'
    workingDirectory: build/lib/all_test/Release/
    displayName: 'Run Tests'
  - script: 'Get-PSReadlineOption'
    displayName: 'PSReadlineOption'

- phase: LinuxSelfHost
  queue:
    name: 'Hosted Ubuntu 1604'
  steps:
  - script: 'ls'
    displayName: 'list'
  - script: 'Get-PSReadlineOption'
    displayName: 'PSReadlineOption'
  - script: 'dpkg --list | grep compiler'
    displayName: 'list compilers'
  - script: 'mkdir build'
    displayName: 'mkdir build'
  - script: 'cp CMakeLists.txt build/'
    displayName: 'cp CMakeLists'
  - script: 'cmake generators --help'
    displayName: 'cmake generators'
  - script: 'export CC=/usr/local/bin/gcc-7'
    displayName: 'set gcc version'
  - script: 'export CXX=/usr/local/bin/g++-7'
    displayName: 'set g++ version'
  - script: 'cmake CMakeLists.txt'
    displayName: 'cmake'
#  - task: CMake@1
#    displayName: 'CMake@1'
  - script: 'make AllTest'
    displayName: 'Build AllTest'
  - script: 'ls -R'
    displayName: 'list recursive'
  - script: 'cd lib/all_test'
    displayName: 'set all test directory'
  - script: 'ls -l'
    displayName: 'list detailed'
  - script: './AllTest'
    workingDirectory: lib/all_test/
    displayName: 'run AllTest'
  